SELECT * FROM STUDENT_DETAIL;
SELECT  ROLLNO + MARKS AS ADD_RESULT FROM STUDENT_DETAIL;
SELECT  ROLLNO - MARKS AS SUB_RESULT FROM STUDENT_DETAIL;
SELECT  ROLLNO * MARKS AS PROD_RESULT FROM STUDENT_DETAIL;
SELECT  ROLLNO % MARKS AS MODULO_RESULT FROM STUDENT_DETAIL;
SELECT  ROLLNO / MARKS AS DIV_RESULT FROM STUDENT_DETAIL;