CREATE DATABASE NUMBER;
USE NUMBER;
CREATE TABLE AGREGATE(
NEW_ID INT,
NEW_CAT VARCHAR(90)
);
INSERT INTO AGREGATE(NEW_ID,NEW_CAT)
VALUES
(100,"AGNI"),
(200,"AGNI"),
(500,"DIYA"),
(700,"DIYA"),
(200,"RISHABH"),
(300,"RISHABH"),
(500,"RISHABH");
SELECT * FROM AGREGATE;
SELECT NEW_ID,NEW_CAT,
SUM(NEW_ID) OVER(PARTITION BY NEW_CAT ORDER BY NEW_ID ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS "TOTAL",
MAX(NEW_ID) OVER(PARTITION BY NEW_CAT ORDER BY NEW_ID ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS "MAX",
MIN(NEW_ID) OVER(PARTITION BY NEW_CAT ORDER BY NEW_ID) AS "MIN",
COUNT(NEW_ID) OVER(PARTITION BY NEW_CAT ORDER BY NEW_ID ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS "COUNT",
AVG(NEW_ID) OVER(PARTITION BY NEW_CAT ORDER BY NEW_ID ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS "AVERAGE"
FROM AGREGATE;
 


