CREATE DATABASE NUMBER;
USE NUMBER;
CREATE TABLE AGREGATE(
NEW_ID INT,
NEW_CAT VARCHAR(90)
);
INSERT INTO AGREGATE(NEW_ID,NEW_CAT)
VALUES
(100,"AGNI"),
(200,"AGNI"),
(200,"DIYA"),
(300,"DIYA"),
(500,"RISHABH"),
(500,"RISHABH"),
(700,"RISHABH");
SELECT * FROM AGREGATE;
SELECT NEW_ID,NEW_CAT,
SUM(NEW_ID) OVER( ORDER BY NEW_ID ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) AS "TOTAL",
MAX(NEW_ID) OVER( ORDER BY NEW_ID  ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS "MAX",
MIN(NEW_ID) OVER( ORDER BY NEW_ID  ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS "MIN",
COUNT(NEW_ID) OVER( ORDER BY NEW_ID  ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS "COUNT",
AVG(NEW_ID) OVER( ORDER BY NEW_ID  ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS "AVERAGE"
FROM AGREGATE;
 


