SELECT * FROM AGREGATE;
SELECT NEW_ID,
FIRST_VALUE(NEW_ID ) OVER( ORDER BY NEW_ID ) AS "FIRST_VALUE",
LAST_VALUE(NEW_ID ) OVER( ORDER BY NEW_ID ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) AS "LAST_VALUE",
LEAD(NEW_ID ) OVER( ORDER BY NEW_ID  ) AS "LEAD",
LAG(NEW_ID ) OVER( ORDER BY NEW_ID  ) AS "LAG"
FROM AGREGATE;
 