SELECT * FROM AGREGATE;
SELECT NEW_ID,NEW_CAT,
ROW_NUMBER() OVER( ORDER BY NEW_ID  ) AS "ROW_NUMBER",
RANK() OVER( ORDER BY NEW_ID  ) AS "RANK",
DENSE_RANK() OVER( ORDER BY NEW_ID  ) AS "DENSE_RANK",
PERCENT_RANK() OVER( ORDER BY NEW_ID  ) AS "PERCENT_RANK"
FROM AGREGATE;
 
