USE SCHOOL ;
INSERT INTO STUDENT_INFO(GRADE,MARKS,FULL_NAME,ID)
VALUES 
('A',-23,"DIYA",2128),
('B',-84,"JIYA",2179),
('D',-23,"SIYA",2234);
SELECT * FROM STUDENT_INFO;
SELECT ABS(MARKS) ,FULL_NAME FROM STUDENT_INFO;