CREATE USER 'KOMAL'@'LOCALHOST' IDENTIFIED BY 'KOMAL@123';
SELECT USER FROM MYSQL.USER;
GRANT  ALL PRIVILEGES ON *.*  TO 'KOMAL'@'LOCALHOST' ;
FLUSH PRIVILEGES;
USE PAYMENTS;
GRANT SELECT ,INSERT ON PAY_INFO2 TO 'KOMAL'@'LOCALHOST' ;

REVOKE  ALL PRIVILEGES ON *.*  FROM 'KOMAL'@'LOCALHOST' ;
GRANT SELECT ,INSERT,DELETE ON PAY_INFO2 TO 'KOMAL'@'LOCALHOST' ;

REVOKE    INSERT ON *.*  FROM 'KOMAL'@'LOCALHOST' ;