CREATE USER KITTU IDENTIFIED BY "KITTU@123";
USE BANK;
GRANT SELECT,UPDATE ON DEPT TO KITTU ;
SELECT USER FROM MYSQL.USER;
CREATE USER ABC IDENTIFIED BY "ABC@123";
USE BANK;
GRANT SELECT,UPDATE ON DEPT TO ABC ;