CREATE DATABASE GIFTSHOP;
USE GIFTSHOP;
CREATE TABLE GIFT(
GIFTNAME VARCHAR(90),
PRICE INT );
INSERT INTO GIFT (GIFTNAME,PRICE)
VALUES
("TOY",23440),
("RING",1500),
("TADDY",2300),
("ROSE",232),
("DIAMOND",24375),
("BRACELET",2000),
("CAKE",1000);
SELECT * FROM GIFT;
SELECT GIFTNAME,PRICE,
CASE  PRICE
WHEN 2300 THEN "MODERATE PRICE"
WHEN  24375 THEN "MOST EXPENSIVE"
WHEN  23440 THEN "MOST EXPENSIVE"
ELSE "REGULAR PRICE"
END
AS ANLYSIS_TEXT
FROM GIFT;

