USE INSTITUTE;
CREATE TABLE EMPLOYEE_2(
MANAGER_ID VARCHAR(90),
ID INT PRIMARY KEY ,
NAME VARCHAR(90)
);

INSERT INTO EMPLOYEE_2
VALUES
( 103,101,"RISHI"),
(104,109,"RISHA"),
(NULL,106,"VIVEK"),
( 103,104,"MADHU");
SELECT * FROM EMPLOYEE_2 ;
SELECT  ID  FROM EMPLOYEE 
EXCEPT
SELECT ID FROM EMPLOYEE_2 ;




