CREATE TABLE PAY_INFO(
NAME VARCHAR(90),
MODE VARCHAR(90),
PAY_DATE DATETIME,
ID INT);
INSERT INTO PAY_INFO(NAME,MODE,PAY_DATE,ID)
VALUES
("KHUSHI","NETBANKING", '2015-05-1 12:45:10.9',2),
("JIYA","PAYTM", '2013-08-12 11:40:19.20',4),
("RAHUL","COD", '2019-09-28 18:45:10.4',1),
("BHAWNA","NETBANKING", '2025-02-18 22:32:11.9',11),
("RISHIKA","PAYTM", '2025-07-17 14:41:20.7',10),
("ANVI","COD", '2011-11-25 12:45:10.9',19);
SELECT * FROM PAY_INFO;
SELECT  NAME, MODE, PAY_DATE ,DATE_FORMAT(   PAY_DATE, '%W,%M,%d,%Y') AS FORMATED_DATE FROM PAY_INFO;
SELECT  NAME, MODE, PAY_DATE ,DATE_FORMAT(   PAY_DATE, '%W,%M,%j,%Y,%r') AS FORMATED_DATE FROM PAY_INFO;
SELECT  NAME, MODE, PAY_DATE ,DATE_FORMAT(   PAY_DATE, '%W,%M,%d,%Y,%S') AS FORMATED_DATE FROM PAY_INFO;
SELECT  NAME, MODE, PAY_DATE ,DATE_FORMAT(   PAY_DATE, '%W,%M,%d,%Y,%s') AS FORMATED_DATE FROM PAY_INFO;
SELECT  NAME, MODE, PAY_DATE ,DATE_FORMAT(   PAY_DATE, '%W,%M,%d,%Y,%T') AS FORMATED_DATE FROM PAY_INFO;
SELECT  NAME, MODE, PAY_DATE ,DATE_FORMAT(   PAY_DATE, '%W,%M,%d,%Y,%H') AS FORMATED_DATE FROM PAY_INFO;
SELECT  NAME, MODE, PAY_DATE ,DATE_FORMAT(   PAY_DATE, '%W,%M,%d,%Y,%f') AS FORMATED_DATE FROM PAY_INFO;
SELECT  NAME, MODE, PAY_DATE ,DATE_FORMAT(   PAY_DATE, '%W,%M,%d,%Y,%h') AS FORMATED_DATE FROM PAY_INFO;