USE BIRTHDAY_DETAILS;
SELECT * FROM BIRTHDAY_INFO;
BEGIN;
UPDATE BIRTHDAY_INFO SET NAME ="RISHU" WHERE  NAME ="MADHU";
DELETE FROM BIRTHDAY_INFO WHERE NAME = "KHUSHI";
ROLLBACK;
SELECT * FROM BIRTHDAY_INFO;