USE BANK ;
CREATE TABLE WORKERS(
NAME VARCHAR(90),
AGE INT,
ID INT);
INSERT INTO WORKERS 
VALUES
("KHUSHI",NULL,0),
("RIYA",20,0),
("JIYA",0,34),
("VISHI",22,67),
("RIYA",52,0),
("RISHIKA",33,NULL);
SELECT  *,ISNULL(ID) AS ISNULL_RESULT FROM WORKERS ;