USE PAYMENTS; 
 SELECT *,EXTRACT(  HOUR FROM PAY_DATE ) AS TIME  FROM  PAY_INFO2 ;
 SELECT *,EXTRACT(  MINUTE FROM PAY_DATE ) AS TIME FROM  PAY_INFO2;
 SELECT*, EXTRACT(  SECOND FROM PAY_DATE ) AS TIME FROM  PAY_INFO2;
 SELECT *,EXTRACT(  MICROSECOND  FROM PAY_DATE ) AS TIME FROM  PAY_INFO2;
