USE BANK;
CREATE TABLE ABC(
SN INT  ,NAME VARCHAR(90)
);
CREATE INDEX  IDX_NAME ON ABC(NAME);
INSERT INTO ABC (SN,NAME)
VALUES
(3,'KHUSHI'),
(2,'AADII'),
(4,'SAM'),
(5,'TOM'),
(7,'RUCHI');
SELECT * FROM ABC;
SHOW   INDEXES FROM ABC;
DROP INDEX IDX_NAME ON  ABC;