USE SCHOOL ;
CREATE TABLE STUDENT(
GRADE VARCHAR(90),
MARKS INT,
NAME VARCHAR(90)
);
INSERT INTO STUDENT 
VALUES
("D",34,"KHUSHI"),
("A",89,"RIYA"),
("C",50,"NIKHIL"),
("B",67,"RONIT"),
("B",70,"RONITA");
SELECT * FROM STUDENT;
ALTER TABLE STUDENT
 RENAME TO STUDENT_INFO; 
SET SQL_SAFE_UPDATES=0;
SELECT * FROM STUDENT;