USE SCHOOL ;
CREATE TABLE STUDENT(
GRADE VARCHAR(90),
MARKS INT,
FULL_NAME VARCHAR(90)
);
INSERT INTO STUDENT 
VALUES
("D",34,"KHUSHI"),
("A",89,"RIYA"),
("C",50,"NIKHIL"),
("B",67,"RONIT"),
("B",70,"RONITA");
SELECT * FROM STUDENT_info  WHERE  binary FULL_NAME LIKE 'r%';
SELECT * FROM STUDENT_info WHERE FULL_NAME LIKE 'R%';